version: 1
amp:
  host: http://localhost:8080
  username: admin
  password: admin
servers:
  server1:
    name: Minecraft01
    id: 1ty3j38u
  server2:
    name: Minecraft02
    id: h9kl6f4j
  server3:
    name: Minecraft03
    id: l4g7kd98
  server4:
    name: Minecraft04
    id: 9d5hjd7i

# Experimental feature, still a work in progress
groups:
  minigames:
    name: Minigames
    servers:
      - server1
      - server3
    tasks:
      restart:
        command: restart
        interval: 60 # in seconds
        conditions:
          - placeholder: playercount
            operator: ==
            value: 0

  community:
    name: Community
    servers:
      - server2
      - server4
