name: ServerPanelManager
version: '${version}'
author: p0t4t0sandwich
description: A plugin that allows you to manage your Panel's game servers from within minecraft
main: dev.neuralnexus.serverpanelmanager.bukkit.BukkitSPMPlugin
depend: []
softdepend: [LuckPerms]
folia-supported: true
commands:
  psm:
    description: "A command that allows you to manage your Panel's game servers from within minecraft"
    usage: /psm <command> [args]
    aliases: [amp]
    permission: psm.amp
