name: AMPServerManager
version: '${version}'
main: ca.sperrer.p0t4t0sandwich.panelservermanager.bukkit.BukkitMain
folia-supported: true
commands:
  psm:
    description: "PanelServerManager is a plugin that allows you to manage your Panel's servers from within Minecraft."
    usage: /psm <command> [args]
    aliases: [amp]
    permission: psm.amp
